#!/usr/bin/env python

#write the private key generated by add_keypair.py to a file to use it later

import novaclient.v2.client as nvclient
import os
nova = nvclient.Client(...)
keypair_name = "test-key"
private_key_filename = "/home/raghu/id-test-key"
keypair = nova.keypairs.create(name=keypair_name)

# Create a file for writing that can only be read and written by
owner
fp = os.open(private_key_filename, os.O_WRONLY | os.O_CREAT, 0o600)
with os.fdopen(fp, 'w') as f:
    f.write(keypair.private_key)